# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_feature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11get_feature.proto\"\x18\n\x07Request\x12\r\n\x05image\x18\x01 \x01(\x0c\"V\n\x08Response\x12\x17\n\x01\x63\x18\x01 \x03(\x0b\x32\x0c.Response.R1\x1a\x31\n\x02R1\x12\x1a\n\x01\x62\x18\x01 \x03(\x0b\x32\x0f.Response.R1.R0\x1a\x0f\n\x02R0\x12\t\n\x01\x61\x18\x01 \x03(\x02\x32\x32\n\x0bGrpcService\x12#\n\ngetFeature\x12\x08.Request\x1a\t.Response\"\x00\x42\x11Z\x0c./getfeature\x80\x01\x01\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_RESPONSE_R1 = _RESPONSE.nested_types_by_name['R1']
_RESPONSE_R1_R0 = _RESPONSE_R1.nested_types_by_name['R0']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'get_feature_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'R1' : _reflection.GeneratedProtocolMessageType('R1', (_message.Message,), {

    'R0' : _reflection.GeneratedProtocolMessageType('R0', (_message.Message,), {
      'DESCRIPTOR' : _RESPONSE_R1_R0,
      '__module__' : 'get_feature_pb2'
      # @@protoc_insertion_point(class_scope:Response.R1.R0)
      })
    ,
    'DESCRIPTOR' : _RESPONSE_R1,
    '__module__' : 'get_feature_pb2'
    # @@protoc_insertion_point(class_scope:Response.R1)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'get_feature_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.R1)
_sym_db.RegisterMessage(Response.R1.R0)

_GRPCSERVICE = DESCRIPTOR.services_by_name['GrpcService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014./getfeature\200\001\001'
  _REQUEST._serialized_start=21
  _REQUEST._serialized_end=45
  _RESPONSE._serialized_start=47
  _RESPONSE._serialized_end=133
  _RESPONSE_R1._serialized_start=84
  _RESPONSE_R1._serialized_end=133
  _RESPONSE_R1_R0._serialized_start=118
  _RESPONSE_R1_R0._serialized_end=133
  _GRPCSERVICE._serialized_start=135
  _GRPCSERVICE._serialized_end=185
# @@protoc_insertion_point(module_scope)
